Repository googleapis/nodejs-phishing-protection, pull requests merged in 2020-08, with the labels that each got.

#175 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#179 feat(build): add github summary check workflow
  .github/workflows/summary_check.yml
Labels: cla: yes

#184 fix: bump action version
  .github/workflows/summary_check.yml
Labels: cla: yes

#185 build: bump version action version
  .github/workflows/summary_check.yml
Labels: cla: yes

#186 build: bump action version
  .github/workflows/summary_check.yml
Labels: cla: yes

#187 build: bump action version
  .github/workflows/summary_check.yml
Labels: automerge, cla: yes

#188 build: bump action version
  .github/workflows/summary_check.yml
Labels: cla: yes

#190 build: update kokoro config/unblock rotted test
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  samples/test/quickstart.js
  synth.metadata
  system-test/test.ts
Labels: cla: yes

#193 fix: modify apiCall
  src/v1beta1/phishing_protection_service_v1_beta1_client.ts
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: none

#178 build: use gapic-generator-typescript v1.0.7.
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: full

#194 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: full
