Repository googleapis/nodejs-phishing-protection, pull requests merged in 2020-07, with the labels that each got.

#159 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#160 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#162 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#164 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#167 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#168 build: missing closing paren in publish script, delete template for Node 8, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#169 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#170 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#171 fix: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#172 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#174 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
