Repository googleapis/nodejs-phishing-protection, pull requests merged in 2020-05, with the labels that each got.

#144 fix: regenerate unit tests
  synth.metadata
  test/gapic_phishing_protection_service_v1_beta1_v1beta1.ts
Labels: automerge, cla: yes

#146 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#147 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
