Repository googleapis/nodejs-phishing-protection, pull requests merged in 2020-11, with the labels that each got.

#218 build: remove Node 13 file
  .github/sync-repo-settings.yaml
Labels: api: phishingprotection, cla: yes

#217 build: updates to kokoro
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: none

#220 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1beta1/phishing_protection_service_v1_beta1_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: phishingprotection, automerge, cla: yes

#224 fix: check for fetch on window
  protos/protos.json
  src/v1beta1/phishing_protection_service_v1_beta1_client.ts
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: none
