Repository googleapis/nodejs-phishing-protection, pull requests merged in 2021-01, with the labels that each got.

#230 build: update required status checks
  .github/sync-repo-settings.yaml
Labels: api: phishingprotection, cla: yes

#231 docs: update dates
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  src/v1beta1/index.ts
  src/v1beta1/phishing_protection_service_v1_beta1_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_phishing_protection_service_v1_beta1_v1beta1.ts
Labels: api: phishingprotection, automerge, cla: yes, context: none

#227 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: full

#232 build: update checks appropriately
  .github/sync-repo-settings.yaml
Labels: api: phishingprotection, cla: yes

#228 chore: generate GAPIC metadata JSON file
  src/v1beta1/gapic_metadata.json
  synth.metadata
Labels: api: phishingprotection, cla: yes, context: full

#233 feat: adds style enumeration
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: none

#237 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: phishingprotection, automerge, cla: yes, context: full
